config/routes.rb
Rails.application.routes.draw do
  get 'about-us' => "my_pages#about_us"
  get 'contact-us'=>"my_pages#contact_us"
  get 'privacy-policy'=> "my_pages#privacy_policy"
  root "pages#home"

  resources :employees
  resources :documents

  get "up" => "rails/health#show", as: :rails_health_check


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/demo.rb
class Demo < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :documents
  validates :first_name , :last_name , presence: true
  validates  :personal_email , presence:true, uniqueness:true
  validates  :salary, :city,:state,:pincode ,:country,:address_line_1 , presence:true
  def name
    "#{first_name} #{last_name}".strip
  end
  def address
    "#{address_line_1} , #{city} ,#{state} ".strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController<ApplicationController
  def index
     @documents=Document.all
  end
end

app/controllers/employees_controller.rb
class EmployeesController <ApplicationController
  before_action :set_employee ,only: [ :edit, :update, :show  , :destroy]
    def index #all
     @employees=Employee.all()
    end
    def new
      @employee=Employee.new
    end
    def edit
    end
    def update
      if  @employee.update(employee_params)
                redirect_to employees_path
      else
          render :edit
      end

    end
    def show  #by id

    end
    # create
    def create

         if @employee.save
                     redirect_to employees_path , notice: "Employee Successfully created"
         else
          render :new
         end

    end
    def destroy
            if @employee.destroy
                            redirect_to employees_path , notice: "Employee deleted"
            end
    end
   private
   def employee_params
         params.require(:employee).permit(:first_name,:last_name,:personal_email,:salary,:pincode,:city,:state,:address_line_1,:country)
   end
   def set_employee
         @employee=Employee.find(params[:id])
   end
end

app/controllers/my_pages_controller.rb
class MyPagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title_text="hello world!"
    @subtitle_text= "I am learning rails!!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/documents/index.html.erb
<h1><%@documents.each do |document|%></h1>
    Employee name: <h3><%=link_to document.employee.name, employee_path(document.employee)%></h3>
    documents: 
    <h4><%=document.name%></h4>
    <h4><%=document.doc_type%></h4>

<%end%>

app/views/employees/edit.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 mb-5">
        <div class="card-body">
            <h1 class="text-center">Upadate Employee</h1>
        </div>
    </div>
</div>

<%=render "shared/form", employee:@employee%>

app/views/employees/index.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 mb-5">
        <div class="card-body">
            <h2 class="text-center">Listing Employees</h2>

        </div>
    </div>
    <%=flash[:notice] %>
    <%=link_to "Create New Employee",new_employee_path,class:"btn btn-primary mb-4 rounded-0" %>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Sr No.</th>
                <th>Name</th>
                <th>Email</th>
                <th>Address</th>
                <th>Salary</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <%@employees.each do |employee|%>
            <tr>
                <th><%=employee.id%></th>
                <th>
                    <%=employee.name%>
                </th>
                <th>
                    <%=employee.personal_email%>
                </th>
                <th>
                    <%=employee.address%>
                </th>
                <th>
                    <%=employee.salary%>
                </th>
                <th>
                    <%=link_to "edit", edit_employee_path(employee.id) ,class:"btn btn-primary rounded-0"%>
                    <%=link_to "show", employee_path(employee.id) ,class:"btn btn-primary rounded-0"%>
                    <%=link_to "delete", employee_path(employee),method: :delete,data: { confirm: 'Are you sure?' },class:"btn btn-primary rounded-0"%>
                </th>
            </tr>
                
            <%end%>
        </tbody>
    </table>
</div>

app/views/employees/new.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 mb-5">
        <div class="card-body">
            <h1 class="text-center">Create New Employee</h1>
        </div>
    </div>
</div>

<%=render "shared/form", employee:@employee  %>

app/views/employees/show.html.erb
<h1>Employee Details</h1>
<h3>name: <%=@employee.name%></h3>
<h3>address: <%=@employee.address%></h3>
<h3>salary : <%=@employee.salary%></h3>
<h3>pincode: <%=@employee.pincode%></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Omrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
   <%=render "shared/header"%>
   <div class="container">
      <div class="row">
      <%= yield %>
      </div>
    <div>
      <%=render "shared/footer"%>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

app/views/my_pages/about_us.html.erb
<div class="col-lg-10 mx-auto">
    <h1 class="text-center">About us</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At varius vel pharetra vel turpis nunc eget. Adipiscing enim eu turpis egestas pretium aenean. Aliquet sagittis id consectetur purus ut. Mattis molestie a iaculis at. Et molestie ac feugiat sed lectus vestibulum mattis. Enim eu turpis egestas pretium. Fames ac turpis egestas maecenas. Platea dictumst quisque sagittis purus sit amet volutpat. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Nulla aliquet porttitor lacus luctus accumsan. Vel turpis nunc eget lorem dolor. Turpis egestas maecenas pharetra convallis. Mattis pellentesque id nibh tortor id aliquet lectus proin. At augue eget arcu dictum varius duis. Diam ut venenatis tellus in metus vulputate. Tristique senectus et netus et malesuada fames. Nunc aliquet bibendum enim facilisis gravida neque convallis.</p>

<p>Neque volutpat ac tincidunt vitae semper quis lectus nulla at. Malesuada bibendum arcu vitae elementum curabitur. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Pellentesque habitant morbi tristique senectus et netus et. Ultrices vitae auctor eu augue ut lectus. Rhoncus aenean vel elit scelerisque mauris pellentesque. Feugiat sed lectus vestibulum mattis ullamcorper velit. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Purus viverra accumsan in nisl nisi scelerisque. Turpis egestas sed tempus urna. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Pretium fusce id velit ut tortor pretium viverra.</p>

<p>Eu lobortis elementum nibh tellus. Eget mauris pharetra et ultrices. Volutpat sed cras ornare arcu. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Consectetur adipiscing elit duis tristique sollicitudin nibh. Faucibus interdum posuere lorem ipsum dolor sit amet. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. In pellentesque massa placerat duis ultricies lacus sed turpis. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc. In arcu cursus euismod quis viverra nibh. Mattis nunc sed blandit libero. Bibendum neque egestas congue quisque. Quisque non tellus orci ac auctor augue mauris augue. Maecenas ultricies mi eget mauris. Vulputate dignissim suspendisse in est ante. Elementum nibh tellus molestie nunc non blandit. Molestie a iaculis at erat pellentesque. Et ultrices neque ornare aenean euismod elementum nisi quis.</p>

</div>

app/views/my_pages/contact_us.html.erb
<div class="col-lg-10 mx-auto">
    <h1 class="text-center mt-5 mb-4">Contact us</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At varius vel pharetra vel turpis nunc eget. Adipiscing enim eu turpis egestas pretium aenean. Aliquet sagittis id consectetur purus ut. Mattis molestie a iaculis at. Et molestie ac feugiat sed lectus vestibulum mattis. Enim eu turpis egestas pretium. Fames ac turpis egestas maecenas. Platea dictumst quisque sagittis purus sit amet volutpat. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Nulla aliquet porttitor lacus luctus accumsan. Vel turpis nunc eget lorem dolor. Turpis egestas maecenas pharetra convallis. Mattis pellentesque id nibh tortor id aliquet lectus proin. At augue eget arcu dictum varius duis. Diam ut venenatis tellus in metus vulputate. Tristique senectus et netus et malesuada fames. Nunc aliquet bibendum enim facilisis gravida neque convallis.</p>

<p>Neque volutpat ac tincidunt vitae semper quis lectus nulla at. Malesuada bibendum arcu vitae elementum curabitur. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Pellentesque habitant morbi tristique senectus et netus et. Ultrices vitae auctor eu augue ut lectus. Rhoncus aenean vel elit scelerisque mauris pellentesque. Feugiat sed lectus vestibulum mattis ullamcorper velit. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Purus viverra accumsan in nisl nisi scelerisque. Turpis egestas sed tempus urna. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Pretium fusce id velit ut tortor pretium viverra.</p>

<p>Eu lobortis elementum nibh tellus. Eget mauris pharetra et ultrices. Volutpat sed cras ornare arcu. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Consectetur adipiscing elit duis tristique sollicitudin nibh. Faucibus interdum posuere lorem ipsum dolor sit amet. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. In pellentesque massa placerat duis ultricies lacus sed turpis. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc. In arcu cursus euismod quis viverra nibh. Mattis nunc sed blandit libero. Bibendum neque egestas congue quisque. Quisque non tellus orci ac auctor augue mauris augue. Maecenas ultricies mi eget mauris. Vulputate dignissim suspendisse in est ante. Elementum nibh tellus molestie nunc non blandit. Molestie a iaculis at erat pellentesque. Et ultrices neque ornare aenean euismod elementum nisi quis.</p>

</div>

app/views/my_pages/privacy_policy.html.erb
<div class="col-lg-10 mx-auto">
    <h1 class="text-center mt-5 mb-4">Privacy Policy</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At varius vel pharetra vel turpis nunc eget. Adipiscing enim eu turpis egestas pretium aenean. Aliquet sagittis id consectetur purus ut. Mattis molestie a iaculis at. Et molestie ac feugiat sed lectus vestibulum mattis. Enim eu turpis egestas pretium. Fames ac turpis egestas maecenas. Platea dictumst quisque sagittis purus sit amet volutpat. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Nulla aliquet porttitor lacus luctus accumsan. Vel turpis nunc eget lorem dolor. Turpis egestas maecenas pharetra convallis. Mattis pellentesque id nibh tortor id aliquet lectus proin. At augue eget arcu dictum varius duis. Diam ut venenatis tellus in metus vulputate. Tristique senectus et netus et malesuada fames. Nunc aliquet bibendum enim facilisis gravida neque convallis.</p>

<p>Neque volutpat ac tincidunt vitae semper quis lectus nulla at. Malesuada bibendum arcu vitae elementum curabitur. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Pellentesque habitant morbi tristique senectus et netus et. Ultrices vitae auctor eu augue ut lectus. Rhoncus aenean vel elit scelerisque mauris pellentesque. Feugiat sed lectus vestibulum mattis ullamcorper velit. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Purus viverra accumsan in nisl nisi scelerisque. Turpis egestas sed tempus urna. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Pretium fusce id velit ut tortor pretium viverra.</p>

<p>Eu lobortis elementum nibh tellus. Eget mauris pharetra et ultrices. Volutpat sed cras ornare arcu. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Consectetur adipiscing elit duis tristique sollicitudin nibh. Faucibus interdum posuere lorem ipsum dolor sit amet. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. In pellentesque massa placerat duis ultricies lacus sed turpis. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc. In arcu cursus euismod quis viverra nibh. Mattis nunc sed blandit libero. Bibendum neque egestas congue quisque. Quisque non tellus orci ac auctor augue mauris augue. Maecenas ultricies mi eget mauris. Vulputate dignissim suspendisse in est ante. Elementum nibh tellus molestie nunc non blandit. Molestie a iaculis at erat pellentesque. Et ultrices neque ornare aenean euismod elementum nisi quis.</p>

</div>

app/views/pages/home.html.erb
<h1><%= @title_text%></h1>
<p><%=@subtitle_text%></p>
<div class="text-center">
  <h1 class="mb-5">welcome to ONE month ruby course</h1>
<h3>Destination for web developers who aspire to be the best </h3>  
</div>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="py-5">
    <div class="row">
      <div class="col-2">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>

      <div class="col-2">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>

      <div class="col-2">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>

      
    </div>

    <div class="d-flex justify-content-between py-4 my-4 border-top">
      <p>&copy; 2021 Company, Inc. All rights reserved.</p>
      <ul class="list-unstyled d-flex">
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
      </ul>
    </div>
  </footer>
</div>

app/views/shared/_form.html.erb
<%=form_with model:employee do |form| %>
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <%=form.label :first_name, class:"mb-2"%>
                <%=form.text_field :first_name, class:"form-control rounded-0"%>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                <%=form.label :last_name, class:"mb-2"%>
                <%=form.text_field :last_name, class:"form-control rounded-0"%>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="form-group">
                <%=form.label :personal_email, class:"mb-2"%>
                <%=form.text_field :personal_email, class:"form-control rounded-0"%>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                <%=form.label :salary, class:"mb-2"%>
                <%=form.number_field :salary, class:"form-control rounded-0"%>
            </div>
        </div>
        
        <div class="col-lg-3">
            <div class="form-group">
                <%=form.label :address_line_1, class:"mb-2"%>
                <%=form.text_field :address_line_1, class:"form-control rounded-0"%>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                <%=form.label :city, class:"mb-2"%>
                <%=form.text_field :city, class:"form-control rounded-0"%>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                <%=form.label :pincode, class:"mb-2"%>
                <%=form.text_field :pincode, class:"form-control rounded-0"%>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                <%=form.label :state, class:"mb-2"%>
                <%=form.text_field :state, class:"form-control rounded-0"%>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group">
                <%=form.label :country, class:"mb-2"%>
                <%=form.text_field :country, class:"form-control rounded-0"%>
            </div>
        </div>
        
            <div class="row">
                <div class="col-lg-12">
                    <%=form.submit class:"btn btn-primary btn-lg rounded-0 mt-5"%>
                    <%=link_to "Back to Employees", employees_path, class:"btn btn-primary btn-lg rounded-0 mt-5"%>
                </div>
            </div>
    </div>
<%end%>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary ">
  <div class="container-fluid">
    <%=link_to "Om Rails", root_path,class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path,class:"nav-link active" %>  
        </li>
        <li class="nav-item">
          <%=link_to "About us" , about_us_path, class:"nav-link active"%>
        </li>
        <li class="nav-item ">           
         <%=link_to "Contact us", contact_us_path, class: "nav-link active"%>          
        </li>
        <li class="nav-item ">           
         <%=link_to "Privacy Policy", privacy_policy_path, class: "nav-link active"%>          
        </li>
        
      </ul>
      
    </div>
  </div>
</nav>